### PR TITLE
Added support for specifying the interpreter path

### PR DESCRIPTION
**Pull request by jlafon**
Adds support for specifying a path to an alternate Python interpreter.

### CODE REVIEW

**Comment by jlafon** [comment]
So far, I've been unable to reproduce the travis test failures locally. Apologies for all of the chatter, but I have no other way of debugging the issue.

**Comment by jlafon** [comment]
It looks like pip search running on the travis VM was emitting some non ascii characters.

**Comment by sjkingo** [comment]
This is excellent - much needed. And awesome for fixing the broken tests! Will merge today.

Thanks very much

**Comment by sjkingo** [comment]
Merged, and published the changes as version 2.1.3, now available on PyPi/pip
Thanks again for your input

**Pull request merged**
