### PR TITLE
Add a function to allow creating wheels of python packages

### PR DESCRIPTION
**Pull request by rmb938**

### CODE REVIEW

**Comment by sjkingo** [comment]
Looks good - are you able to write a test function and add a small description to the `README.md` file so I can merge it?

**Comment by rmb938** [comment]
Yup no problem. Will get that done later tonight

**Comment by rmb938** [comment]
alright test is written and readme has been updated

**Comment by sjkingo** [comment]
Excellent, that all looks really good. I like the addition of the wheel package check too, and your test helped me understand what's going on under the hood with `pip wheel`.

Would you be able to do one last thing before I accept, and that's to rebase the commits into one with a descriptive commit message?

Thanks

**Comment by sjkingo** [comment]
If you've not done that before, this helped me the first time:

https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

(specifically with GH, you need to force push as you're rewriting history)

**Comment by rmb938** [comment]
alright the commits are now squashed. If you can push the updated version to pypi once merged that would be awesome.

**Comment by sjkingo** [comment]
Done. 2.1.4 is available on PyPi now and I also distributed a wheel on PyPi for `virtualenv-api`.

Thanks for the contribution!

**Pull request merged**
