### PR TITLE
Fix encoding problem

### PR DESCRIPTION
**Pull request by EcmaXp**

### CODE REVIEW

**Comment by EcmaXp** [comment]
didn't test on python2, sorry.

**Comment by sjkingo** [comment]
Hi, what seems to be the problem you were trying to solve? afaik the README doesn't have any utf-8 characters in it.

**Comment by EcmaXp** [comment]
`Verbose output from each command is available in the environment’s build.log file, which is appended to with each operation. Any errors are logged to build.err.`

I think `’` cause UnicodeDecodeError.

```python
>>> open("README.rst").read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 2831: illegal multibyte sequence
```

**Comment by sjkingo** [comment]
Nice catch! The apostrophe in environment is a utf-8 one not standard ANSI '

Will push a fix shortly.

**Pull request closed without merging**
