### PR TITLE
Fix is_installed for non-lowercase package names

### LINKED ISSUE #38: Packages with capitalized names give the wrong result for is_installed
Try this:

```sh
$ pip install Pillow
$ ipython
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from virtualenvapi.manage import VirtualEnvironment

In [2]: env = VirtualEnvironment('.venv')

In [3]: env.installed_package_names
Out[3]:
[
 ...
 'pillow',
 'pip',
 ...
]

In [4]: env.is_installed('Pillow')
Out[4]: False

In [5]: env.installed_packages
Out[5]:
[
 ('Pillow', '5.3.0'),
 ('pip', '18.1'),
 ...
]
```

It looks like `installed_package_names` would lowercase all the package names, so the check for whether the package is installed would wrongly return False.

### PR DESCRIPTION
**Pull request by irvinlim**
Fixes #38.

### CODE REVIEW

**Comment by sjkingo** [comment]
Thanks for the PR. Would you be able to fix the tests for this change:

https://travis-ci.org/sjkingo/virtualenv-api/jobs/453874924

**Comment by irvinlim** [comment]
Hi @sjkingo, it looks like the tests have been failing before this PR already: https://travis-ci.org/sjkingo/virtualenv-api/builds/436743179

It looks like the `--use-wheel` pip command-line argument has been deprecated, causing the [first test failure](https://travis-ci.org/sjkingo/virtualenv-api/jobs/453874924#L472-L477): https://stackoverflow.com/a/49835917/2037090

On the other hand, I'm not sure how to fix the second test failure, is it a transient failure?

Should I fix these unrelated tests in this PR, or create a separate PR for this?

**Comment by irvinlim** [comment]
Once #40 is merged, I will rebase this PR onto master, and add some test cases for capitalization as well.

**Comment by irvinlim** [comment]
Hold on with the merge, I think tests should be failing but Travis is using the wrong branch

**Comment by sjkingo** [comment]
Thanks! Have merged and released 2.1.17 on pypi

**Pull request merged**
